[2022-01-23 02:14:12,665] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: stocks_dag.get_financials_ manual__2022-01-23T02:14:09.123920+00:00 [queued]>
[2022-01-23 02:14:12,677] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: stocks_dag.get_financials_ manual__2022-01-23T02:14:09.123920+00:00 [queued]>
[2022-01-23 02:14:12,678] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-23 02:14:12,678] {taskinstance.py:1239} INFO - Starting attempt 1 of 4
[2022-01-23 02:14:12,679] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-23 02:14:12,690] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): get_financials_> on 2022-01-23 02:14:09.123920+00:00
[2022-01-23 02:14:12,696] {standard_task_runner.py:52} INFO - Started process 2178 to run task
[2022-01-23 02:14:12,701] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'stocks_dag', 'get_financials_', 'manual__2022-01-23T02:14:09.123920+00:00', '--job-id', '569', '--raw', '--subdir', 'DAGS_FOLDER/stocks_dag.py', '--cfg-path', '/tmp/tmph1fiwfsk', '--error-file', '/tmp/tmpha6vvrc_']
[2022-01-23 02:14:12,702] {standard_task_runner.py:77} INFO - Job 569: Subtask get_financials_
[2022-01-23 02:14:12,761] {logging_mixin.py:109} INFO - Running <TaskInstance: stocks_dag.get_financials_ manual__2022-01-23T02:14:09.123920+00:00 [running]> on host 313081f76d55
[2022-01-23 02:14:12,826] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=mcgaritym@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=stocks_dag
AIRFLOW_CTX_TASK_ID=get_financials_
AIRFLOW_CTX_EXECUTION_DATE=2022-01-23T02:14:09.123920+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-23T02:14:09.123920+00:00
[2022-01-23 02:14:13,089] {logging_mixin.py:109} INFO - AAPL 1
[2022-01-23 02:14:22,785] {logging_mixin.py:109} INFO - MSFT 2
[2022-01-23 02:14:31,742] {logging_mixin.py:109} INFO - GOOGL 3
[2022-01-23 02:14:41,282] {logging_mixin.py:109} INFO - GOOG 4
[2022-01-23 02:14:50,927] {logging_mixin.py:109} INFO - AMZN 5
[2022-01-23 02:15:01,251] {logging_mixin.py:109} INFO - TSLA 6
[2022-01-23 02:15:10,143] {logging_mixin.py:109} INFO - FB 7
[2022-01-23 02:15:19,885] {logging_mixin.py:109} INFO - NVDA 8
[2022-01-23 02:15:30,197] {logging_mixin.py:109} INFO - TSM 9
[2022-01-23 02:15:39,121] {logging_mixin.py:109} INFO - JPM 10
[2022-01-23 02:15:48,863] {logging_mixin.py:109} INFO - V 11
[2022-01-23 02:15:58,099] {logging_mixin.py:109} INFO - KeyError:  'Earnings'
[2022-01-23 02:15:58,100] {logging_mixin.py:109} INFO - JNJ 12
[2022-01-23 02:16:08,294] {logging_mixin.py:109} INFO - UNH 13
[2022-01-23 02:16:18,149] {logging_mixin.py:109} INFO - BAC 14
[2022-01-23 02:16:27,988] {logging_mixin.py:109} INFO - HD 15
[2022-01-23 02:16:37,590] {logging_mixin.py:109} INFO - WMT 16
[2022-01-23 02:16:47,640] {logging_mixin.py:109} INFO - PG 17
[2022-01-23 02:16:57,874] {logging_mixin.py:109} INFO - MA 18
[2022-01-23 02:17:07,581] {logging_mixin.py:109} INFO - BABA 19
[2022-01-23 02:17:17,422] {logging_mixin.py:109} INFO - PFE 20
[2022-01-23 02:17:27,459] {logging_mixin.py:109} INFO - ASML 21
[2022-01-23 02:17:36,767] {logging_mixin.py:109} INFO - XOM 22
[2022-01-23 02:17:46,711] {logging_mixin.py:109} INFO - KeyError:  'trailingPE'
[2022-01-23 02:17:46,712] {logging_mixin.py:109} INFO - DIS 23
[2022-01-23 02:17:56,248] {logging_mixin.py:109} INFO - TM 24
[2022-01-23 02:18:07,496] {logging_mixin.py:109} INFO - NTES 25
[2022-01-23 02:18:17,733] {logging_mixin.py:109} INFO - KO 26
[2022-01-23 02:18:27,167] {logging_mixin.py:109} INFO - CSCO 27
[2022-01-23 02:18:37,078] {logging_mixin.py:109} INFO - AVGO 28
[2022-01-23 02:18:46,496] {logging_mixin.py:109} INFO - ADBE 29
[2022-01-23 02:18:56,462] {logging_mixin.py:109} INFO - LLY 30
[2022-01-23 02:19:06,161] {logging_mixin.py:109} INFO - TMO 31
[2022-01-23 02:19:15,909] {logging_mixin.py:109} INFO - CVX 32
[2022-01-23 02:19:25,220] {logging_mixin.py:109} INFO - ABBV 33
[2022-01-23 02:19:35,346] {logging_mixin.py:109} INFO - PEP 34
[2022-01-23 02:19:45,137] {logging_mixin.py:109} INFO - ABT 35
[2022-01-23 02:19:54,700] {logging_mixin.py:109} INFO - NFLX 36
[2022-01-23 02:20:05,559] {logging_mixin.py:109} INFO - ORCL 37
[2022-01-23 02:20:15,801] {logging_mixin.py:109} INFO - NKE 38
[2022-01-23 02:20:26,147] {logging_mixin.py:109} INFO - ACN 39
[2022-01-23 02:20:36,481] {logging_mixin.py:109} INFO - NVO 40
[2022-01-23 02:20:46,017] {logging_mixin.py:109} INFO - CMCSA 41
[2022-01-23 02:20:56,358] {logging_mixin.py:109} INFO - COST 42
[2022-01-23 02:21:06,495] {logging_mixin.py:109} INFO - CRM 43
[2022-01-23 02:21:16,160] {logging_mixin.py:109} INFO - VZ 44
[2022-01-23 02:21:26,083] {logging_mixin.py:109} INFO - INTC 45
[2022-01-23 02:21:35,589] {logging_mixin.py:109} INFO - WFC 46
[2022-01-23 02:21:45,093] {logging_mixin.py:109} INFO - DHR 47
[2022-01-23 02:21:55,655] {logging_mixin.py:109} INFO - PYPL 48
[2022-01-23 02:22:04,853] {logging_mixin.py:109} INFO - MRK 49
[2022-01-23 02:22:15,206] {logging_mixin.py:109} INFO - NVS 50
[2022-01-23 02:22:24,325] {logging_mixin.py:109} INFO - QCOM 51
[2022-01-23 02:22:33,315] {logging_mixin.py:109} INFO - MCD 52
[2022-01-23 02:22:42,643] {logging_mixin.py:109} INFO - T 53
[2022-01-23 02:22:52,789] {logging_mixin.py:109} INFO - MS 54
[2022-01-23 02:23:01,792] {logging_mixin.py:109} INFO - UPS 55
[2022-01-23 02:23:10,990] {logging_mixin.py:109} INFO - AZN 56
[2022-01-23 02:23:20,946] {logging_mixin.py:109} INFO - SCHW 57
[2022-01-23 02:23:30,366] {logging_mixin.py:109} INFO - LIN 58
[2022-01-23 02:23:39,333] {logging_mixin.py:109} INFO - TXN 59
[2022-01-23 02:23:49,982] {logging_mixin.py:109} INFO - LOW 60
[2022-01-23 02:23:59,956] {logging_mixin.py:109} INFO - NEE 61
[2022-01-23 02:24:09,994] {logging_mixin.py:109} INFO - SAP 62
[2022-01-23 02:24:20,035] {logging_mixin.py:109} INFO - INTU 63
[2022-01-23 02:24:29,675] {logging_mixin.py:109} INFO - UNP 64
[2022-01-23 02:24:39,191] {logging_mixin.py:109} INFO - RY 65
[2022-01-23 02:24:49,011] {logging_mixin.py:109} INFO - BHP 66
[2022-01-23 02:24:59,034] {logging_mixin.py:109} INFO - AMD 67
[2022-01-23 02:25:08,674] {logging_mixin.py:109} INFO - BBL 68
[2022-01-23 02:25:18,815] {logging_mixin.py:109} INFO - PM 69
[2022-01-23 02:25:29,371] {logging_mixin.py:109} INFO - SONY 70
[2022-01-23 02:25:39,077] {logging_mixin.py:109} INFO - HON 71
[2022-01-23 02:25:49,432] {logging_mixin.py:109} INFO - BMY 72
[2022-01-23 02:26:00,070] {logging_mixin.py:109} INFO - KeyError:  'trailingPE'
[2022-01-23 02:26:00,072] {logging_mixin.py:109} INFO - TD 73
[2022-01-23 02:26:10,004] {logging_mixin.py:109} INFO - SHOP 74
[2022-01-23 02:26:19,578] {logging_mixin.py:109} INFO - MDT 75
[2022-01-23 02:26:29,972] {logging_mixin.py:109} INFO - UL 76
[2022-01-23 02:26:39,476] {logging_mixin.py:109} INFO - CVS 77
[2022-01-23 02:26:48,830] {logging_mixin.py:109} INFO - TTE 78
[2022-01-23 02:26:58,347] {logging_mixin.py:109} INFO - HSBC 79
[2022-01-23 02:27:08,483] {logging_mixin.py:109} INFO - AXP 80
[2022-01-23 02:27:18,520] {logging_mixin.py:109} INFO - RTX 81
[2022-01-23 02:27:27,967] {logging_mixin.py:109} INFO - GS 82
[2022-01-23 02:27:37,869] {logging_mixin.py:109} INFO - AMAT 83
[2022-01-23 02:27:46,869] {logging_mixin.py:109} INFO - BLK 84
[2022-01-23 02:27:56,844] {logging_mixin.py:109} INFO - TMUS 85
[2022-01-23 02:28:06,130] {logging_mixin.py:109} INFO - HDB 86
[2022-01-23 02:28:16,482] {logging_mixin.py:109} INFO - C 87
[2022-01-23 02:28:26,219] {logging_mixin.py:109} INFO - AMGN 88
[2022-01-23 02:28:36,134] {logging_mixin.py:109} INFO - SNY 89
[2022-01-23 02:28:45,463] {logging_mixin.py:109} INFO - SBUX 90
[2022-01-23 02:28:55,499] {logging_mixin.py:109} INFO - KeyError:  'Earnings'
[2022-01-23 02:28:55,500] {logging_mixin.py:109} INFO - CHTR 91
[2022-01-23 02:29:04,730] {logging_mixin.py:109} INFO - BA 92
[2022-01-23 02:29:13,697] {logging_mixin.py:109} INFO - KeyError:  'trailingPE'
[2022-01-23 02:29:13,699] {logging_mixin.py:109} INFO - DEO 93
[2022-01-23 02:29:23,867] {logging_mixin.py:109} INFO - EL 94
[2022-01-23 02:29:33,188] {logging_mixin.py:109} INFO - AMT 95
[2022-01-23 02:29:44,545] {logging_mixin.py:109} INFO - CAT 96
[2022-01-23 02:29:55,215] {logging_mixin.py:109} INFO - RIO 97
[2022-01-23 02:30:04,511] {logging_mixin.py:109} INFO - DE 98
[2022-01-23 02:30:14,241] {logging_mixin.py:109} INFO - ISRG 99
[2022-01-23 02:30:23,889] {logging_mixin.py:109} INFO - NOW 100
[2022-01-23 02:30:33,184] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/pymysql/connections.py", line 756, in _write_bytes
    self._sock.sendall(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/airflow/.local/lib/python3.7/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/airflow/.local/lib/python3.7/site-packages/pymysql/connections.py", line 547, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/home/airflow/.local/lib/python3.7/site-packages/pymysql/connections.py", line 814, in _execute_command
    self._write_bytes(packet)
  File "/home/airflow/.local/lib/python3.7/site-packages/pymysql/connections.py", line 760, in _write_bytes
    CR.CR_SERVER_GONE_ERROR, "MySQL server has gone away (%r)" % (e,)
pymysql.err.OperationalError: (2006, "MySQL server has gone away (BrokenPipeError(32, 'Broken pipe'))")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/get_financials.py", line 226, in get_financials
    df_financials.to_sql(name='stock_financials', con=connection_2, if_exists='replace')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 2789, in to_sql
    method=method,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 610, in to_sql
    method=method,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 1406, in to_sql
    table.create()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 736, in create
    if self.exists():
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 720, in exists
    return self.pd_sql.has_table(self.name, self.schema)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 1458, in has_table
    self.connectable.dialect.has_table, name, schema or self.meta.schema
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2212, in run_callable
    return conn.run_callable(callable_, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1653, in run_callable
    return callable_(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/dialects/mysql/base.py", line 2622, in has_table
    ).execute(st)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1003, in execute
    return self._execute_text(object_, multiparams, params)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1178, in _execute_text
    parameters,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/airflow/.local/lib/python3.7/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/airflow/.local/lib/python3.7/site-packages/pymysql/connections.py", line 547, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/home/airflow/.local/lib/python3.7/site-packages/pymysql/connections.py", line 814, in _execute_command
    self._write_bytes(packet)
  File "/home/airflow/.local/lib/python3.7/site-packages/pymysql/connections.py", line 760, in _write_bytes
    CR.CR_SERVER_GONE_ERROR, "MySQL server has gone away (%r)" % (e,)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2006, "MySQL server has gone away (BrokenPipeError(32, 'Broken pipe'))")
[SQL: DESCRIBE `stock_financials`]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
[2022-01-23 02:30:33,202] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=stocks_dag, task_id=get_financials_, execution_date=20220123T021409, start_date=20220123T021412, end_date=20220123T023033
[2022-01-23 02:30:33,212] {standard_task_runner.py:92} ERROR - Failed to execute job 569 for task get_financials_
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/pymysql/connections.py", line 756, in _write_bytes
    self._sock.sendall(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/airflow/.local/lib/python3.7/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/airflow/.local/lib/python3.7/site-packages/pymysql/connections.py", line 547, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/home/airflow/.local/lib/python3.7/site-packages/pymysql/connections.py", line 814, in _execute_command
    self._write_bytes(packet)
  File "/home/airflow/.local/lib/python3.7/site-packages/pymysql/connections.py", line 760, in _write_bytes
    CR.CR_SERVER_GONE_ERROR, "MySQL server has gone away (%r)" % (e,)
pymysql.err.OperationalError: (2006, "MySQL server has gone away (BrokenPipeError(32, 'Broken pipe'))")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/get_financials.py", line 226, in get_financials
    df_financials.to_sql(name='stock_financials', con=connection_2, if_exists='replace')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 2789, in to_sql
    method=method,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 610, in to_sql
    method=method,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 1406, in to_sql
    table.create()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 736, in create
    if self.exists():
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 720, in exists
    return self.pd_sql.has_table(self.name, self.schema)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 1458, in has_table
    self.connectable.dialect.has_table, name, schema or self.meta.schema
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2212, in run_callable
    return conn.run_callable(callable_, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1653, in run_callable
    return callable_(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/dialects/mysql/base.py", line 2622, in has_table
    ).execute(st)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1003, in execute
    return self._execute_text(object_, multiparams, params)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1178, in _execute_text
    parameters,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/airflow/.local/lib/python3.7/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/airflow/.local/lib/python3.7/site-packages/pymysql/connections.py", line 547, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/home/airflow/.local/lib/python3.7/site-packages/pymysql/connections.py", line 814, in _execute_command
    self._write_bytes(packet)
  File "/home/airflow/.local/lib/python3.7/site-packages/pymysql/connections.py", line 760, in _write_bytes
    CR.CR_SERVER_GONE_ERROR, "MySQL server has gone away (%r)" % (e,)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2006, "MySQL server has gone away (BrokenPipeError(32, 'Broken pipe'))")
[SQL: DESCRIBE `stock_financials`]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
[2022-01-23 02:30:33,255] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-01-23 02:30:33,284] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
